version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    labels:
      - dependencies
      - npm
    commit-message:
      prefix: "chore(deps)"
      include: scope
    groups:
      typescript:
        patterns:
          - "typescript"
          - "tsx"
          - "@types/*"
      next-stack:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      radix:
        patterns:
          - "@radix-ui/*"
      lint-format:
        patterns:
          - "eslint*"
          - "prettier*"
          - "@commitlint/*"
      test-stack:
        patterns:
          - "vitest"
          - "@vitest/*"
          - "@playwright/*"
          - "playwright"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "chore(ci)"
      include: scope
