// AUTO-GENERATED by apps/docs/scripts/sync-skills.mjs — DO NOT EDIT BY HAND.
// Re-run: node apps/docs/scripts/sync-skills.mjs
// Source of truth: dash-electric/dash-skills (private sibling repo).

export type SkillReference = {
  label: string
  path: string
}

export type SkillMeta = {
  /** Folder slug — also the public URL stem (/skills/<slug>.md). */
  slug: string
  /** Skill name from frontmatter. */
  name: string
  /** Human title for cards/headings. */
  title: string
  description: string
  version: string
  owner: string
  /** Public path to the self-contained markdown bundle (the LLM link). */
  rawPath: string
  /** Bundle size in bytes. */
  bytes: number
  references: SkillReference[]
}

// Note: the public origin (staging vs prod) is NOT baked in here — it is
// resolved at runtime from env via lib/site-url.ts (getSiteUrl), so the same
// build serves correct links on any deployment.

export const skills: SkillMeta[] = [
  {
    "slug": "dash-deck-design",
    "name": "dash-deck-design",
    "title": "Dash Deck Design",
    "description": "Apply the Dash Electric deck design system (tokens, type, color, charts, layouts) when building, editing, or restyling any Dash deck, slides, presentation, recap, pitch, proposal, postmortem, WBR, strategic memo, speaker intro, war-story / case-study, multi-talk session, or architecture diagram. Output is editorial HTML exported to PDF, never .pptx. Use even if unasked.",
    "version": "0.7.0",
    "owner": "dash-electric",
    "rawPath": "/skills/dash-deck-design.md",
    "bytes": 270018,
    "references": [
      {
        "label": "base-styles.css",
        "path": "/skills/dash-deck-design/references/base-styles.css"
      },
      {
        "label": "design-system.md",
        "path": "/skills/dash-deck-design/references/design-system.md"
      },
      {
        "label": "examples/dash-core-problem-deck.html",
        "path": "/skills/dash-deck-design/references/examples/dash-core-problem-deck.html"
      },
      {
        "label": "examples/mcd-2month-recap.html",
        "path": "/skills/dash-deck-design/references/examples/mcd-2month-recap.html"
      },
      {
        "label": "pattern-map.md",
        "path": "/skills/dash-deck-design/references/pattern-map.md"
      }
    ]
  }
]

export const skillBySlug = (slug: string): SkillMeta | undefined =>
  skills.find((s) => s.slug === slug)
